= The Plan

Ideal setup for the server is the following: Host website for user/admin to 
identify what they want monitored and what machines on the network are allowed to 
pull the config from the server. All the clients will be pointed to this server
to the pull the config that will be auto generated from the website.

== Flow of website

=== Initial setup page

Initial setup will ask the user to list how many teams (int), what kinds of systems 
are being monitored (Name of system OS), ask what is to be monitored for each system
(configs).

=== Main page

Show realtime updates from clients' results to monitor competition.
Has a seperate Admin only page for changing operating system configs, adding/removing
teams, and some other stuff.

== Technology Used

=== Frontend
* `Next.js` for the framework and `Sass` for the styling.

=== Backend
* `Actix-web.rs` for the backend api along with the `SQLx` crate for communicating
with the database.
* `Serde` for serializing and deserializing communications with server and client.
* `MySQL` database hosted in a `Docker` container.
